language: go
go:
  - '1.11'

os:
  - linux
services: docker

env:
  ## Required external variables:
  ##   - DOCKER_USER, DOCKER_PASS
  ##   - GH_TOKEN, GH_KUBECONFIG_PATH
  global:
    - DEPLOYMENTS="merlin-api merlin-frontend"
    - RELEASE_BRANCH=master

    - DOCKER_COMPOSE_VERSION="1.23.2"
    - GOBIN="$GOPATH/bin"
    - BIN_PATH=/opt/bin

cache:
  directories:
    ## Preserve external tools.
    - $BIN_PATH
    ## Preserve golint executable.
    - $GOBIN
    ## Preserve Go module cache.
    - $GOPATH/pkg/mod/cache

## Install external tools.
before_install:
  - export PATH=$BIN_PATH:$PATH
  - ./scripts/tools.sh
  - git fetch --tags  # fetch git tags.


## Install dependencies.
install: export GO111MODULE=on && make ci-install

## Run tests.
script: make ci-test

## Deploy to Docker Hub and Kubernetes.
deploy:
  provider: script
  script: ./scripts/deploy.sh
  skip-cleanup: true
  on:
    all_branches: true

# ## Upload code coverage results.
# after_success:
#   - bash <(curl -s https://codecov.io/bash)
