## This docker-compose config file is used to define build processes for the
## images in this repository, and for development deployment.
##
## It is not meant for use in production deployments. See the deployment/
## directory for production deployment configurations.

version: "3.7"

services:
  api:
    image: "stevenxie/merlin.api:${VERSION}"
    build:
      context: .
      dockerfile: api.Dockerfile
      args:
        BUILD_VERSION: "${VERSION}"
      cache_from:
        - stevenxie/merlin.api:latest
        - alpine:3.8
        - golang:alpine
    container_name: api
    # depends_on:
    #   - entrypoint
    networks:
      - public
    ports:
      - "3000:3000" # for development


networks:
  public:
