## This docker-compose config file is used to define build processes for the
## images in this repository, and for development deployment.
##
## It is not meant for use in production deployments. See the deployment/
## directory for production deployment configurations.

version: "3.4"

services:
  frontend:
    image: "stevenxie/merlin-frontend:${VERSION}"
    build:
      context: .
      dockerfile: ./client/Dockerfile
      args:
        BUILD_VERSION: "${VERSION}"
      cache_from:
        - stevenxie/merlin-frontend:latest
        - nginx:1-alpine
    container_name: frontend
    networks:
      - public
    ports:
      - "8080:80" # for development

  api:
    image: "stevenxie/merlin-api:${VERSION}"
    build:
      context: .
      dockerfile: ./api/Dockerfile
      args:
        BUILD_VERSION: "${VERSION}"
      cache_from:
        - stevenxie/merlin-api:latest
        - alpine:3.8
    container_name: api
    environment:
      - GO_ENV=development
    networks:
      - public
    ports:
      - "3000:3000" # for development


networks:
  public:
