---

apiVersion: apps/v1
kind: Deployment

metadata:
  name: merlin-frontend
  namespace: default

spec:
  replicas: 1
  selector:
    matchLabels:
      app: merlin-frontend
      tier: frontend
      track: stable
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: merlin-frontend
        tier: frontend
        track: stable
    spec:
      containers:
        - name: merlin-frontend
          image: "stevenxie/merlin-frontend"
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 80
